// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function publicSupabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List active security products from Triple A Tech Solutions, optionally filtered by category or search term.",
  inputSchema: {
    category: z.string().optional().describe("Filter by product category."),
    search: z.string().optional().describe("Search term matched against product name."),
    limit: z.number().int().optional().describe("Max products to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, search, limit }) => {
    const supabase = publicSupabase();
    let query = supabase.from("products").select("id, name, description, category, price, stock_status, image_url").eq("is_active", true).order("display_order", { ascending: true }).limit(Math.min(limit ?? 20, 100));
    if (category) query = query.eq("category", category);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-testimonials.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function publicSupabase2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_testimonials_default = defineTool2({
  name: "list_testimonials",
  title: "List testimonials",
  description: "List approved customer testimonials for Triple A Tech Solutions.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Max testimonials to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = publicSupabase2();
    const { data, error } = await supabase.from("testimonials").select("id, name, role, content, rating, created_at").eq("approved", true).order("created_at", { ascending: false }).limit(Math.min(limit ?? 20, 100));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { testimonials: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-product-inquiry.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function publicSupabase3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var submit_product_inquiry_default = defineTool3({
  name: "submit_product_inquiry",
  title: "Submit product inquiry",
  description: "Submit a product inquiry / quote request to Triple A Tech Solutions. Optionally reference a product by id.",
  inputSchema: {
    customer_name: z3.string().describe("Full name of the person inquiring."),
    customer_email: z3.string().describe("Contact email address."),
    customer_phone: z3.string().describe("Contact phone number."),
    message: z3.string().describe("What the customer is interested in."),
    product_id: z3.string().optional().describe("Optional product id from list_products.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ customer_name, customer_email, customer_phone, message, product_id }) => {
    const name = customer_name.trim();
    const email = customer_email.trim();
    const phone = customer_phone.trim();
    if (!name || !email || !phone || !message.trim()) {
      return { content: [{ type: "text", text: "Name, email, phone and message are required." }], isError: true };
    }
    const supabase = publicSupabase3();
    const { data, error } = await supabase.from("product_inquiries").insert({
      product_id: product_id ?? null,
      customer_name: name,
      customer_email: email,
      customer_phone: phone,
      message: message.trim()
    }).select("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Inquiry submitted. The team will get back to you shortly." }],
      structuredContent: { id: data?.[0]?.id }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "triple-a-tech-mcp",
  title: "Triple A Tech Solutions MCP",
  version: "0.1.0",
  instructions: "Tools for Triple A Tech Solutions, a Kenyan security & tech company. Use `list_products` to browse security products, `list_testimonials` for customer reviews, and `submit_product_inquiry` to send a quote request.",
  tools: [list_products_default, list_testimonials_default, submit_product_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
