// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List active security products from Triple A Tech Solutions, optionally filtered by category or search term.",
  inputSchema: {
    category: z.string().optional().describe("Filter by product category."),
    search: z.string().optional().describe("Search term matched against product name."),
    limit: z.number().int().optional().describe("Max products to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("id, name, description, category, price, stock_status, image_url").eq("is_active", true).order("display_order", { ascending: true }).limit(Math.min(limit ?? 20, 100));
    if (category) query = query.eq("category", category);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-testimonials.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_testimonials_default = defineTool2({
  name: "list_testimonials",
  title: "List testimonials",
  description: "List approved customer testimonials for Triple A Tech Solutions.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Max testimonials to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("testimonials").select("id, name, role, content, rating, created_at").eq("approved", true).order("created_at", { ascending: false }).limit(Math.min(limit ?? 20, 100));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { testimonials: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-product-inquiry.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var submit_product_inquiry_default = defineTool3({
  name: "submit_product_inquiry",
  title: "Submit product inquiry",
  description: "Submit a product inquiry / quote request to Triple A Tech Solutions. Optionally reference a product by id.",
  inputSchema: {
    customer_name: z3.string().trim().min(1).max(120).describe("Full name of the person inquiring."),
    customer_email: z3.string().trim().email().max(200).describe("Contact email address."),
    customer_phone: z3.string().trim().min(7).max(30).describe("Contact phone number."),
    message: z3.string().trim().min(1).max(2e3).describe("What the customer is interested in."),
    product_id: z3.string().uuid().optional().describe("Optional product id from list_products.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ customer_name, customer_email, customer_phone, message, product_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("product_inquiries").insert({
      product_id: product_id ?? null,
      customer_name,
      customer_email,
      customer_phone,
      message
    }).select("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Inquiry submitted. The team will get back to you shortly." }],
      structuredContent: { id: data?.[0]?.id }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tltjgqzilkofuwyjhmjy";
var mcp_default = defineMcp({
  name: "triple-a-tech-mcp",
  title: "Triple A Tech Solutions MCP",
  version: "0.1.0",
  instructions: "Tools for Triple A Tech Solutions, a Kenyan security & tech company. Use `list_products` to browse security products, `list_testimonials` for customer reviews, and `submit_product_inquiry` to send a quote request.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, list_testimonials_default, submit_product_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
